databases:
  - name: budgetpal
    databaseName: budgetpal_yviz
    user: budgetpal_yviz_user

services:
  - type: web
    name: budgetpal
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetpal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
